feat: Data lifecycle management inside sessions
aneoconsulting/ArmoniK.Community pull request #33
Opened 2023-09-22 13:10 UTC by melflitty

2023-09-22 14:19 UTC, aneojgurhem commented on AEP/aep-000003.md
> +| Paused                                                               |   ?                           | Allowed                                             |
```suggestion
| Paused                                                               |   Allowed but not Submitted                | Allowed                                             |
```

2023-09-22 14:19 UTC, aneojgurhem commented on AEP/aep-000003.md
> +  rpc GetSession(GetSessionRequest) returns (GetSessionResponse) {} // why curly braces? should i have curly braces in others instead of ;
Let's use `;` for simplicity. Both are valid

2023-09-22 14:19 UTC, aneojgurhem commented on AEP/aep-000003.md
> +The current CancelSession method
sentence !

2023-10-17 08:00 UTC, lemaitre-aneo commented
I think `Terminated` does not convey the right idea. We should probably look for another name. It is a bit long but `ClosedForSubmission` is probably better.

2023-10-27 13:18 UTC, dbrasseur-aneo commented
Please update the structure of the AEP to what has been set by [AEP-00001](https://github.com/aneoconsulting/ArmoniK.Community/blob/main/AEP/aep-00001.md)

2023-11-08 10:44 UTC, aneojgurhem requested changes

2023-11-08 10:44 UTC, aneojgurhem commented on AEP/aep-00003.md
> +Created: 2023-09-22
The heading has changed as defined in aep 1

2023-11-08 13:41 UTC, aneojgurhem approved these changes

2023-11-08 13:41 UTC, merged